### ISSUE TITLE
Design database tables for storing farming information

### ISSUE THREAD

**Issue by Ragil** [Ragil/Communicate-Indonesia#13]
Describe the ndb tables to store farming information

**Comment by girikuncoro** [comment]
I'll work on this tonight, but not sure where to start

**Comment by girikuncoro** [comment]
What do you think about this? 
https://github.com/Ragil/Communicate-Indonesia/tree/farming-model/app/model/farm

I'll merge if you are fine. The `sell` command doesn't require price input from the farmer, so I guess we can just include with `plant` and `harvest` in the same data model. But I'm a bit confused with the price, what was our conclusion with this when we discussed with Kat? Who is gonna update the price for each crop? (Hutan Biru?) And there's no way we can get price data from farmers (according to their selling), see again our doc:
https://docs.google.com/document/d/1yBkrolKWEzYsKNcL_kX0gpyk9AkrIlapQOLVKRu9rBM/edit#

Also I feel this is too relational (not necessarily ndb), let me know your suggestion

**Comment by Ragil** [comment]
Why do we need a Crop table? Are the crops predefined? Can we have a system that dynamically expands it's database of crops based on user input and also be able to detect spelling errors in crops?

> Also I feel this is too relational (not necessarily ndb), let me know your suggestion

Except for crop table, not really. Two way links are fine. Users have links to districts.

**Comment by Ragil** [comment]
> But I'm a bit confused with the price, what was our conclusion with this when we discussed with Kat? 

We should be able to add price information as future improvements if we've designed the existing data appropriately. For now, we can just store what has been outlined in the doc

**Comment by girikuncoro** [comment]
> Why do we need a Crop table? Are the crops predefined? Can we have a system that dynamically expands it's database of crops based on user input and also be able to detect spelling errors in crops?

I was thinking Crop table will define the unit of a crop as well (I think I missed this last night), since every crop has different unit. But you are correct, better to have dynamic crops since we are not sure all crops available at sites and they may decide to change production. We can ignore unit for now (or I can add unit as property in either `farm` or `price` table?). In this case, I can just change the `crop_id` to `crop_name` in both `farm` and `price` table/kind and remove Crop table. I assume there will be other modules that can list up crops and do something with price.
