### ISSUE TITLE
Implement Harvest action

### ISSUE THREAD

**Issue by Ragil** [Ragil/Communicate-Indonesia#25]
The action should process the harvest operation and update appropriate database entries

**Comment by girikuncoro** [comment]
I'll start on this

**Comment by girikuncoro** [comment]
See #31 , if you are fine with this I'll mimic to #26 and #12 

1. Can you teach me why we need `super()` in this case? I read the docs but still didn't get its practical usage here
2. To `district_id` to `Farm` table, I pulled it from `User` table through the `phone_number`. Is this acceptable?
3. I was thinking to use `i18n` in some parts since the command already involves Indonesian language, but decided not to.

**Comment by Ragil** [comment]
> To store district_id to Farm table, I pulled it from User table through the phone_number. Is this acceptable?

the sms should already have user. https://github.com/Ragil/Communicate-Indonesia/blob/master/app/api/sms/main.py#L45

> I was thinking to use i18n in some parts since the command already involves Indonesian language, but decided not to.

i18n should be used for output. It's an incredible amount of effort to do it correctly for input.

**Comment by girikuncoro** [comment]
Fixed in #34 and then #35
